boxplot(best$Field1Turns, best$Field2Turns, best$Field3Turns, main = "Average Field Visits")
best <- read_csv("C:/Users/kirat/Desktop/MATH4600/MoosingAround/Output - 10P, 50G, 2MNM/best.csv")
run00 <- read_csv("C:/Users/kirat/Desktop/MATH4600/MoosingAround/Output - 10P, 50G, 2MNM/run00.csv")
run00M<-as.matrix(run00)
bestM<-as.matrix(best)
boxplot(bestM$Field1Turns)
boxplot(best$Field1Turns)
boxplot(best$Field1Turns, best$Field2Turns, best$Field3Turns)
boxplot(best$Field1Turns, best$Field2Turns, best$Field3Turns, main = "Average Field Visits", at = c(1,2,3), names = c("Field 1", "Field 2", "Field 3"), col = c("lightsteelblue4","lightsteelblue"), horizontal = TRUE, notch = TRUE)
